### PR TITLE
Pr/datalog rules

### PR DESCRIPTION
**Pull request by CharlesHD**
Okay so this is a first draw where I implement the ideas expressed in #23 
I add : 
+ a  `(reg-query-sub query-id query rules)` form to `reg-query-sub`
+ a `:rules` attribute to `query` config map

### CODE REVIEW

**Comment by denistakeda** [comment]
@CharlesHD `re-posh` heavily depends on `posh` library. And posh supports only subset of `datascript` functionality (which is a subset of `datomic` functionality itself). Have you verified that it works?

**Comment by CharlesHD** [comment]
Not yet, that's why it is a first draw. But my guess is it has high chance to work since `posh.reagent/q` is a direct call to `datascript.core/q` and rules work fine with Datascript. 

I'll add and test a rule example in the todomvc if you are okay with that.

**Comment by denistakeda** [comment]
Sure, it would be great

**Comment by CharlesHD** [comment]
OK. After some investigations, rules are broken in posh5 as stated in https://github.com/mpdairy/posh/issues/23 . So that PR is bounded by some progression in posh. Too bad.

**Pull request closed without merging**
